version: 0.2

env:
  variables:
    PROJECT_NAME: "pygoat"
    REPORT_DIR: "security-reports"

phases:
  install:
    commands:
      - echo "Installing dependencies and security tools..."
      - mkdir -p ${REPORT_DIR}

      # Instala pre-commit
      #- pip install pre-commit

      # Instala Bandit (SAST para Python)
      - pip install bandit

      # Instala librería para interactuar con la API de DefectDojo
      - pip install requests

  pre_build:
    commands:
      # - echo "Running pre-commit hooks as a validation step in CI..."
      # Ejecuta todos los hooks definidos en tu .pre-commit-config.yaml
      # Si algún hook falla, 'pre-commit run' saldrá con un código de error no-cero,
      # lo que hará que esta fase de CodeBuild falle y detenga el pipeline.
      #- pre-commit run --all-files

  build:
    commands:
      - echo "Continuing with main security scans if pre-commit passed..."

      # --- 1. Análisis Estático (SAST) con Bandit (Docker) ---
      - echo "Running SAST with Bandit..."
      # Genera un reporte en JSON. El '|| true' es para que el comando no falle el build
      # si encuentra vulnerabilidades, permitiendo que el reporte se suba a DefectDojo.
      # Si se quiere que el build falle aquí si Bandit encuentra algo, se debe quitar el '|| true'.
      - echo "Ejecutando SAST con Bandit via Docker..."
      - docker run --rm -v "$(pwd)":/src ghcr.io/pycqa/bandit/bandit -r /src -f json -o /src/${REPORT_DIR}/bandit-report.json || true


      # --- 2. Análisis de Composición de Software (SCA) con OWASP Dependency-Check (Docker) ---
      - echo "Running SCA with OWASP Dependency-Check via Docker..."
      - docker pull owasp/dependency-check # Opcional, pero asegura que tienes la última versión
      - docker run --rm -v "$(pwd)":/src:z owasp/dependency-check --scan /src \
          --project "${PROJECT_NAME}" \
          --format JUNIT \
          --out /src/${REPORT_DIR}/dependency-check-report.xml
          --nvdApiKey ${NIST_API_KEY}
          
  post_build:
    commands:
      - echo "Uploading security scan results to DefectDojo with curl..."

      # Sube reporte de Bandit con curl
      - |
        if [ -f "${REPORT_DIR}/bandit-report.json" ]; then
          curl --location --request POST "$DEFECTDOJO_HOST/api/v2/import-scan/" \
          --header "Authorization: Token $DEFECTDOJO_API_KEY" \
          --form "engagement=$DEFECTDOJO_ENGAGEMENT_ID" \
          --form "scan_type=Bandit" \
          --form "active=true" \
          --form "verified=false" \
          --form "tags=cicd-aws-security-pipeline" \
          --form "skip_duplicates=true" \
          --form "title=Bandit SAST Scan - $CODEBUILD_RESOLVED_SOURCE_VERSION" \
          --form "branch=$CODEBUILD_WEBHOOK_HEAD_REF" \
          --form "file=@${REPORT_DIR}/bandit-report.json"
        fi

      # Sube reporte de OWASP Dependency-Check con curl
      - |
        if [ -f "${REPORT_DIR}/dependency-check-report.xml" ]; then
          curl --location --request POST "$DEFECTDOJO_HOST/api/v2/import-scan/" \
          --header "Authorization: Token $DEFECTDOJO_API_KEY" \
          --form "engagement=$DEFECTDOJO_ENGAGEMENT_ID" \
          --form "scan_type=Dependency Check" \
          --form "active=true" \
          --form "verified=false" \
          --form "tags=cicd-aws-security-pipeline" \
          --form "skip_duplicates=true" \
          --form "title=Dependency Check SCA Scan - $CODEBUILD_RESOLVED_SOURCE_VERSION" \
          --form "branch=$CODEBUILD_WEBHOOK_HEAD_REF" \
          --form "file=@${REPORT_DIR}/dependency-check-report.xml"
        fi

artifacts:
  files:
    - '${REPORT_DIR}/**/*'
  discard-paths: no
